### ISSUE TITLE
No output appers

### ISSUE THREAD

**Issue by mjgritli** [73CN0109y-Packages/laravel-helper#2]
Dear All.

while i was very happy with the idea, however, when i issue a command, no output shows up ?
is there anything i'm missing

**Comment by creazy231** [comment]
same problem here :(
the preview image looked awesome but nothing happens when I enter the code e.g. make:model

**Comment by kris-araptus** [comment]
Same for me!

**Comment by AnthoRdev** [comment]
Same for me! Any suggestion?

**Comment by Tecnology73** [comment]
Sorry for the very delayed response all.

If you can try the latest version (v0.2.5) to see if it fix for you all thanks.

**Comment by AnthoRdev** [comment]
Thanks dude that's works !

**Comment by Tecnology73** [comment]
I'm going to close this issue.

If this issue is persisting for you in the latest version, feel free to create a new issue!
