### ISSUE TITLE
Error with composer dumpautoload on Windows-platform

### ISSUE THREAD

**Issue by crasyhorse** [73CN0109y-Packages/laravel-helper#4]
Hi,
Platform: Windows 7
Atom: 1.26.1 x64
laravel-helper: 0.2.5

Error in file _Command.js, line 244

On Windows the command "cd" must use the "/d" switch in case that the project folder is located on another device as Atom (e. g. Atom is installed on drive C: and the project is located on drive D:). Without this switch there is no directory change (rootDirectory points to the correct path but "cd" does nothing).

This could be fixed like that for example:

		let execString = `cd "${rootDirectory}" && ${command}`
		if (process.platform === "win32") {
			execString = `cd /d "${rootDirectory}" && ${command}`
		}
		exec( execString, ( err, stdout, stderr ) => {

Sorry, for this unformatted piece of code but many java scripts are blocked in my browser.

Regards

CrasyHorse

**Comment by Tecnology73** [comment]
Thanks for this insight... Check out v0.2.6 to see if this issue is resolved for you
