### ISSUE TITLE
No issue, just an upgrade suggestion!

### ISSUE THREAD

**Issue by antonioeasystaff** [73CN0109y-Packages/laravel-helper#5]
Hi! Thanks for this useful package. It would be wonderful to have included this package too https://github.com/svenluijten/artisan-view!
Hope you'll think about it. Bye!

**Comment by Tecnology73** [comment]
I'll look into adding the ability to add your own commands via some sort of config file 🤔

**Comment by antonioeasystaff** [comment]
Would be wonderful! Thank you 👍
